curl -C - -O https://alfand.ru/fonts/Comfortaa-Bold.woff
curl -C - -O https://alfand.ru/fonts/Comfortaa-Light.woff
curl -C - -O https://alfand.ru/fonts/Comfortaa-Regular.woff
curl -C - -O https://alfand.ru/fonts/Cuprum-Bold.woff
curl -C - -O https://alfand.ru/fonts/Cuprum-BoldItalic.woff
curl -C - -O https://alfand.ru/fonts/Cuprum-Italic.woff
curl -C - -O https://alfand.ru/fonts/Cuprum-Regular.woff
curl -C - -O https://alfand.ru/fonts/Exo2-Bold.woff
curl -C - -O https://alfand.ru/fonts/Exo2-BoldItalic.woff
curl -C - -O https://alfand.ru/fonts/Exo2-ExtraLight.woff
curl -C - -O https://alfand.ru/fonts/Exo2-ExtraLightItalic.woff
curl -C - -O https://alfand.ru/fonts/Exo2-Italic.woff
curl -C - -O https://alfand.ru/fonts/Exo2-Light.woff
curl -C - -O https://alfand.ru/fonts/Exo2-LightItalic.woff
curl -C - -O https://alfand.ru/fonts/Exo2-Medium.woff
curl -C - -O https://alfand.ru/fonts/Exo2-MediumItalic.woff
curl -C - -O https://alfand.ru/fonts/Exo2-Regular.woff
curl -C - -O https://alfand.ru/fonts/Exo2-SemiBold.woff
curl -C - -O https://alfand.ru/fonts/Exo2-SemiBoldItalic.woff
curl -C - -O https://alfand.ru/fonts/Exo2-Thin.woff
curl -C - -O https://alfand.ru/fonts/Exo2-ThinItalic.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-Bold.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-BoldItalic.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-CondBold.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-CondLight.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-CondLightItalic.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-Italic.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-Light.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-LightItalic.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-Regular.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-Semibold.woff
curl -C - -O https://alfand.ru/fonts/OpenSans-SemiboldItalic.woff
curl -C - -O https://alfand.ru/fonts/Oswald-VariableFont_wght.woff
curl -C - -O https://alfand.ru/fonts/UbuntuCondensed-Regular.woff